# config/routes.yaml

abc_news:
    path: /abc
    controller: App\Controller\NewsController::get_abc_news

rbk_news:
    path: /rbk
    controller: App\Controller\NewsController::get_rbk_news

update_news:
    path: /update-news
    controller: App\Controller\NewsController::update_news

delete_news:
    path: /delete-news
    controller: App\Controller\NewsController::delete_news
